### ISSUE TITLE
自由保守主义

### ISSUE THREAD

**Issue by hfgm1145** [HittyGubby/TNOCreator#2]

**Comment by hfgm1145** [comment]
建议加一个自保的饼图

**Comment by HittyGubby** [comment]
emm，你说的自由保守主义是保守主义的一种吗？ 保守主义是有的，深蓝色饼图

**Comment by hfgm1145** [comment]
> emm，你说的自由保守主义是保守主义的一种吗？保守主义是有的，深蓝色饼图

e我指的是[https://the-new-order-last-days-of-europe.fandom.com/zh/wiki/%E8%87%AA%E7%94%B1%E4%BF%9D%E5%AE%88%E4%B8%BB%E4%B9%89](url)

**Comment by hfgm1145** [comment]
我指的是https://the-new-order-last-days-of-europe.fandom.com/zh/wiki/%E8%87%AA%E7%94%B1%E4%BF%9D%E5%AE%88%E4%B8%BB%E4%B9%89

**Comment by HittyGubby** [comment]
![tno_colors](https://github.com/user-attachments/assets/8b235247-5922-4e67-8dc1-451b3949072e)

好吧，我没怎么注意新版还多了个意识形态，我马上加上

**Comment by HittyGubby** [comment]
可以啦，用用看看有啥问题不
