### ISSUE TITLE
饼图颜色细分

### ISSUE THREAD

**Issue by hfgm1145** [HittyGubby/TNOCreator#3]
将饼图颜色细分化（包括老版秘纳），如图
![2372006e7db30224265a6e541e32f597204096233](https://github.com/user-attachments/assets/6ca8c264-a34f-4505-b9e6-780ddcac39f9)

**Comment by HittyGubby** [comment]
秘传纳是有的，紫色的，除此之外我加了点ooc的内容（EU的虚无主义）
至于饼图细分，因为那个是个小饼图不大看得出来，而且如果加细分的话那个输入框可能会非常多，比较繁琐，我也在考虑要不要新建一个项目单独做饼图

**Comment by HittyGubby** [comment]
迁移到tfr的模式了，随便加颜色 好耶
