### ISSUE TITLE
饼图颜色问题

### ISSUE THREAD

**Issue by WJQMachine** [HittyGubby/TNOCreator#5]
如果是旧版饼图应为：
秘传 52 25 80 #003419
极民 35 35 35 #232323
国社 80 50 0 #005032
束棒 132 50 0 #843200
专制 75 75 75 #4B4B4B
家长 130 130 130 #828282
保守 0 0 135 #000087
自保 39 49 149 #273195
自由 78 97 163 #4E61A3
进步 169 27 79 #A91B4F
社 155 0 0 #9B0000
康 110 0 0 #6E0000
大概是吧，总之现在的蓝色和粉色应该是有问题的

**Comment by HittyGubby** [comment]
![](https://github.com/user-attachments/assets/bc79118b-e222-4a38-b1fd-9218f5de8d23)
嗯！！对味了
感谢！
