### ISSUE TITLE
可否增加选择图标功能？

### ISSUE THREAD

**Issue by TwintailedFox** [HittyGubby/TNOCreator#6]
目前网站要求自行上传图标，而上传大概需要作者介入。建议把大部分tno图标内置到网页里变成选项，只有国旗和领导人两项可自行上传。
如有可能，希望可以多加个国家精神栏

**Comment by TwintailedFox** [comment]
啊没看readme，不是搞程序这行的所以不太懂，当我没说好了

**Comment by HittyGubby** [comment]
没事，我还是说一下好了，那个输入框有两个，第一个是原版素材，你可以自己搜索，第二个才是上传的
另外国家精神似乎不在这个版面呢，如果想加可以截图之后自己加上去
